export enum tagTypes {
  user = "user",
  driver = "driver",
  trip = "trip",
  vehicle = "vehicle",
  tripCost = "tripCost",
  driverSalary = "driverSalary",
  accessory = "accessory",
  request='inventoryRequest',
  officeCost = "officeCost",
  inventory = 'inventory',
  manageRequest = 'manageRequest',
  manageFuel = 'manageFuel',
  income = "income",
  customer = "customer",
  vehicleType = "vehicleType",
  vehicleInspection = "vehicleInspection",
  vendors = "vendors",
  parts = "parts",
  order = "order",
  review = "review",
  expense = "expense"
}

export const tagTypesList = [
  tagTypes.user,
  tagTypes.driver,
  tagTypes.trip,
  tagTypes.vehicle,
  tagTypes.tripCost,
  tagTypes.driverSalary,
  tagTypes.accessory,
  tagTypes.request,
  tagTypes.officeCost,
  tagTypes.inventory,
  tagTypes.manageRequest,
  tagTypes.manageFuel,
  tagTypes.income,
  tagTypes.customer,
  tagTypes.vehicleType,
  tagTypes.vehicleInspection,
  tagTypes.vendors,
  tagTypes.parts,
  tagTypes.order,
  tagTypes.review,
  tagTypes.expense
];
